{
  "Data": {
    "error14": null
  },
  "Errors": [
    {
      "Message": "Value cannot be null. (Parameter 'Error14')",
      "Code": null,
      "Path": [
        "error14"
      ],
      "Locations": [
        {
          "Line": 1,
          "Column": 3
        }
      ],
      "Exception": {
        "ClassName": "System.ArgumentNullException",
        "Message": "Value cannot be null.",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at HotChocolate.Execution.ErrorBehaviourTests.Query.get_Error14() in /Users/michael/local/hc/src/HotChocolate/Core/test/Core.Tests/Execution/Errors/ErrorBehaviourTests.cs:line 420\n   at lambda_method(Closure , IResolverContext )\n   at HotChocolate.Types.FieldMiddlewareCompiler.<>c__DisplayClass3_0.<<CreateResolverMiddleware>b__0>d.MoveNext() in /Users/michael/local/hc/src/HotChocolate/Core/src/Types/Types/Helpers/FieldMiddlewareCompiler.cs:line 74\n--- End of stack trace from previous location where exception was thrown ---\n   at HotChocolate.Execution.ExecutionStrategyBase.ExecuteMiddlewareAsync(ResolverContext resolverContext, IErrorHandler errorHandler) in /Users/michael/local/hc/src/HotChocolate/Core/src/Core/Execution/ExecutionStrategyBase.Resolver.cs:line 40",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": null,
        "HResult": -2147467261,
        "Source": "HotChocolate.Core.Tests",
        "WatsonBuckets": null,
        "ParamName": "Error14"
      },
      "Extensions": {}
    }
  ],
  "Extensions": null,
  "ContextData": null
}
