{
  "Data": {
    "error11": null
  },
  "Extensions": {},
  "Errors": [
    {
      "Message": "Unexpected Execution Error",
      "Code": null,
      "Path": [
        "error11"
      ],
      "Locations": [
        {
          "line": 1,
          "column": 3
        }
      ],
      "Exception": {
        "ClassName": "System.Exception",
        "Message": "query error 11",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at HotChocolate.Execution.ErrorbehaviorTests.Query.get_Error11() in /Users/michael/Local/hotchocolate/src/Core/Core.Tests/Execution/Errors/ErrorbehaviorTests.cs:line 412\n   at lambda_method(Closure , IResolverContext )\n   at HotChocolate.Types.FieldMiddlewareCompiler.<>c__DisplayClass3_0.<<CreateResolverMiddleware>b__0>d.MoveNext() in /Users/michael/Local/hotchocolate/src/Core/Types/Types/Helpers/FieldMiddlewareCompiler.cs:line 74\n--- End of stack trace from previous location where exception was thrown ---\n   at HotChocolate.Execution.ExecutionStrategyBase.ExecuteMiddlewareAsync(ResolverContext resolverContext, IErrorHandler errorHandler) in /Users/michael/Local/hotchocolate/src/Core/Core/Execution/ExecutionStrategyBase.Resolver.cs:line 41",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": null,
        "HResult": -2146233088,
        "Source": "HotChocolate.Core.Tests",
        "WatsonBuckets": null
      },
      "Extensions": {}
    }
  ],
  "ContextData": {}
}
